### PR TITLE
Fix invalid frob & download larger than 1024px

### PR DESCRIPTION
**Pull request by qduc**
Hello,

Thank you for creating this great tool.

I created a PR to fix the "invalid frob" error (#6).

#4 is fixed too.

I hope this can get FlicrkFaves working again.

Cheers.

### CODE REVIEW

**Comment by Lonestar80** [comment]
Thanks so much for your fix!
Was waiting for so long that someone would come forward with a pull request.

**Comment by kilrah** [comment]
Awesome, thanks! Had a try to fix #4 after I posted it but my skills failed...

**Comment by qduc** [comment]
@kilrah Sorry, I have no idea. I'm using jdk 1.8 too and no error here.

Btw, looks like the author is inactive so I made a release with an execuatable jar on my repo.
You can try it here.
https://github.com/qduc/FlickrFaves/releases/tag/v2.0.7

**Comment by magnusvk** [comment]
@qduc thanks for submitting this, sorry for the slow response.

I invited you to be a maintainer for this project, if you don't mind could you merge this and publish a new build here?

Thanks.

**Comment by qduc** [comment]
@magnusvk Sure. I made a new build.

**Comment by magnusvk** [comment]
Amazing, thank you for doing this!

**Comment by qduc** [comment]
You’re welcome!

**Pull request merged**
